//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVirtual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Id { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public Nullable<double> Total { get; set; }
        public string Usuario { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
